apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-green
  namespace: webapps
  labels:
    app: frontend
    version: green
spec: 
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels: 
      app: frontend
      version: green
  template:
    metadata:
      labels:
        app: frontend
        version: green
    spec: 
      serviceAccountName: jenkins
      imagePullSecrets:
      - name: ecr-registry-secret
      containers:
      - name: frontend
        image: 091008253157.dkr.ecr.us-east-1.amazonaws.com/todoapp-frontend:green
        imagePullPolicy: Always
        env:
          - name: REACT_APP_BACKEND_URL
            value: "http://backend-svc:3500/api/tasks"
        ports:
        - containerPort: 3000
